# -*- coding: utf-8 -*-
"""secondfile.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DxQYQ25WXN-icgE1urwTY3_MLy8GtTQQ
"""

# Function to calculate the area of a rectangle
def calculate_rectangle_area(length, width):
    area = length * width
    return area

# Example values for length and width
length = 5
width = 10

# Calculate the area of the rectangle
area_of_rectangle = calculate_rectangle_area(length, width)
print("The area of the rectangle is:", area_of_rectangle)